server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/postgres
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: transaction-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  kafka:
    bootstrap-servers:
     - localhost:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
  cloud:
    function:
      definition: cashbackApproved
    stream:
      bindings:
        cashbackApproved-int-0:
          destination: cashbackApproved
          group: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

rate:
  credit: 0.2